
const KEY='ordini_fornitori_pwa_v14', BACK='ordini_fornitori_pwa_backup', THEME='ordini_theme';
const $=s=>document.querySelector(s); const app=$('#app'); const uuid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const euro=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(n)||0);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=load(), view={page:'home', supplierId:null, histMonth:'all',histSupplier:'all', statsDate:new Date()};
function fresh(){return {format:'OrdiniFornitoriFullBackup',schemaVersion:3,createdAt:Date.now(),suppliers:[{id:uuid(),name:'Fornitore esempio',archived:false,products:[{id:uuid(),name:'Prodotto A',price:2.5,qty:0,unit:'pz'},{id:uuid(),name:'Prodotto B',price:4.9,qty:0,unit:'pz'}]}],history:[]}}
function normalize(x){ if(!x||!Array.isArray(x.suppliers)) return fresh(); x.history=Array.isArray(x.history)?x.history:[]; x.suppliers=x.suppliers.map(s=>({id:s.id||uuid(),name:s.name||'Fornitore',archived:!!s.archived,products:(s.products||[]).map(p=>({id:p.id||uuid(),name:p.name||'Prodotto',price:Math.max(0,+p.price||0),qty:Math.max(0,parseInt(p.qty)||0),unit:(p.unit||'pz').trim()||'pz'}))})); x.history=x.history.map(h=>({id:h.id||uuid(),supplierId:h.supplierId||'',supplierName:h.supplierName||'Fornitore',dateMillis:+h.dateMillis||Date.now(),total:Math.max(0,+h.total||0),items:(h.items||[]).map(i=>({productId:i.productId||'',name:i.name||'Prodotto',price:Math.max(0,+i.price||0),qty:Math.max(0,parseInt(i.qty)||0),unit:i.unit||'pz'}))})); return x }
function load(){try{return normalize(JSON.parse(localStorage.getItem(KEY)))}catch{return fresh()}}
function save(){state.createdAt=Date.now(); try{const old=localStorage.getItem(KEY); if(old)localStorage.setItem(BACK,old); localStorage.setItem(KEY,JSON.stringify(state));}catch{} }
function supplier(id){return state.suppliers.find(s=>s.id===id)}
function total(s){return s.products.reduce((a,p)=>a+p.price*p.qty,0)} function itemCount(s){return s.products.reduce((a,p)=>a+p.qty,0)} function selectedCount(s){return s.products.filter(p=>p.qty>0).length}
function monthTotal(y,m){return state.history.filter(h=>{let d=new Date(h.dateMillis);return d.getFullYear()==y&&d.getMonth()==m}).reduce((a,h)=>a+h.total,0)}
function monthOrders(y,m){return state.history.filter(h=>{let d=new Date(h.dateMillis);return d.getFullYear()==y&&d.getMonth()==m})}
function monthLabel(y,m){return new Date(y,m,1).toLocaleDateString('it-IT',{month:'long',year:'numeric'})}
function setTheme(dark){document.documentElement.classList.toggle('dark',dark);localStorage.setItem(THEME,dark?'dark':'light')}
setTheme(localStorage.getItem(THEME)==='dark');
function topbar(title,sub='',back=false){return `<header class="topbar"><button class="iconbtn" onclick="${back?'goHome()':'openDrawer()'}">${back?'‹':'☰'}</button><div class="top-title"><h1>${esc(title)}</h1>${sub?`<small>${esc(sub)}</small>`:''}</div></header>`}
function render(){ if(view.page==='home')home(); else if(view.page==='supplier')supplierView(); else if(view.page==='history')historyView(); else if(view.page==='stats')statsView(); else if(view.page==='archive')archiveView(); }
function home(){let now=new Date(), mt=monthTotal(now.getFullYear(),now.getMonth());let active=state.suppliers.filter(s=>!s.archived); app.innerHTML=topbar('Ordini Fornitori',`Speso a ${monthLabel(now.getFullYear(),now.getMonth())}: ${euro(mt)}`)+`<main><div class="hero"><div class="row"><div><div class="label">Ordine corrente</div><div class="money">${euro(active.reduce((a,s)=>a+total(s),0))}</div><div class="label">${active.reduce((a,s)=>a+itemCount(s),0)} unità selezionate</div></div><button onclick="showStats()">Statistiche</button></div></div><div class="section-head"><h2>Fornitori</h2><button onclick="editSupplier()">+ Fornitore</button></div><div class="supplier-grid">${active.length?active.map(s=>`<section class="card" draggable="true" data-supplier="${s.id}" ondragstart="dragStart(event)" ondragover="event.preventDefault()" ondrop="dropSupplier(event,'${s.id}')"><div class="supplier-head"><span class="handle">≡</span><div class="supplier-info"><div class="supplier-name">${esc(s.name)}</div><div class="meta">${selectedCount(s)} prodotti selezionati · ${itemCount(s)} unità</div><div class="amount">${euro(total(s))}</div></div><button class="dots" onclick="supplierMenu('${s.id}')">⋮</button></div><div class="actions"><button class="btn primary flex" onclick="openSupplier('${s.id}')">Apri</button></div></section>`).join(''):'<div class="empty">Nessun fornitore attivo.</div>'}</div></main>${orderBottom(active)}`; }
function orderBottom(active){let used=active.filter(s=>itemCount(s)>0);if(!used.length)return '';return `<div class="bottom-summary"><div class="bottom-inner"><div class="grow"><small>${used.length} fornitor${used.length===1?'e':'i'} nell’ordine</small><strong>${euro(used.reduce((a,s)=>a+total(s),0))}</strong></div><button onclick="startShare()">WhatsApp</button></div></div>`}
function openSupplier(id){view={...view,page:'supplier',supplierId:id};render()} function goHome(){view.page='home';view.supplierId=null;render()}
function supplierView(){let s=supplier(view.supplierId);if(!s)return goHome();app.innerHTML=topbar(s.name,`${s.products.length} prodotti`,true)+`<main><div class="section-head"><h2>Prodotti</h2><button onclick="editProduct('${s.id}')">+ Prodotto</button></div>${s.products.length?s.products.map(p=>`<section class="card product" draggable="true" ondragstart="dragProductStart(event,'${p.id}')" ondragover="event.preventDefault()" ondrop="dropProduct(event,'${p.id}')"><div class="prod-top"><span class="handle">≡</span><div class="prod-main"><div class="prod-name">${esc(p.name)}</div><div class="prod-sub">${euro(p.price)} / ${esc(p.unit)}</div></div><button class="dots" onclick="productMenu('${s.id}','${p.id}')">⋮</button></div><div class="stepper"><button onclick="changeQty('${s.id}','${p.id}',-1)">−</button><div><div class="qty">${p.qty}</div><div class="subtotal">${p.qty?euro(p.price*p.qty):'Nessuna quantità'}</div></div><button onclick="changeQty('${s.id}','${p.id}',1)">+</button></div></section>`).join(''):'<div class="empty">Nessun prodotto.</div>'}</main><div class="bottom-summary"><div class="bottom-inner"><div class="grow"><small>${itemCount(s)} unità</small><strong>${euro(total(s))}</strong></div><button onclick="shareOne('${s.id}')">WhatsApp</button></div></div>`}
function changeQty(sid,pid,d){let p=supplier(sid).products.find(x=>x.id===pid);p.qty=Math.max(0,p.qty+d);save();render()}
function editSupplier(id=null){let s=id?supplier(id):null;modal(`<h3>${s?'Modifica':'Nuovo'} fornitore</h3><div class="field"><label>Nome</label><input id="mname" value="${s?esc(s.name):''}" placeholder="Nome fornitore"></div>`,()=>{let n=$('#mname').value.trim();if(!n)return;if(s)s.name=n;else state.suppliers.push({id:uuid(),name:n,archived:false,products:[]});save();closeModal();render()})}
function editProduct(sid,pid=null){let s=supplier(sid),p=pid?s.products.find(x=>x.id===pid):null;modal(`<h3>${p?'Modifica':'Nuovo'} prodotto</h3><div class="field"><label>Nome</label><input id="pname" value="${p?esc(p.name):''}"></div><div class="field"><label>Prezzo</label><input id="pprice" type="number" step="0.01" min="0" value="${p?p.price:''}"></div><div class="field"><label>Unità di misura</label><input id="punit" value="${p?esc(p.unit):'pz'}" placeholder="pz, casse, kg..."></div>`,()=>{let n=$('#pname').value.trim(),pr=Math.max(0,+$('#pprice').value||0),u=$('#punit').value.trim()||'pz';if(!n)return;if(p){p.name=n;p.price=pr;p.unit=u}else s.products.push({id:uuid(),name:n,price:pr,qty:0,unit:u});save();closeModal();render()})}
function supplierMenu(id){let s=supplier(id);modal(`<h3>${esc(s.name)}</h3><button class="menuitem" onclick="closeModal();editSupplier('${id}')">✎ Modifica nome</button><button class="menuitem" onclick="duplicateSupplier('${id}')">⧉ Duplica fornitore</button><button class="menuitem" onclick="archiveSupplier('${id}')">▣ Archivia fornitore</button>`,null,false)}
function duplicateSupplier(id){let s=supplier(id),i=state.suppliers.indexOf(s);state.suppliers.splice(i+1,0,{id:uuid(),name:s.name+' (copia)',archived:false,products:s.products.map(p=>({...p,id:uuid(),qty:0}))});save();closeModal();render()}
function archiveSupplier(id){let s=supplier(id);if(confirm(`Archiviare ${s.name}?`)){s.archived=true;s.products.forEach(p=>p.qty=0);save();closeModal();render()}}
function productMenu(sid,pid){let s=supplier(sid),p=s.products.find(x=>x.id===pid);modal(`<h3>${esc(p.name)}</h3><button class="menuitem" onclick="closeModal();editProduct('${sid}','${pid}')">✎ Modifica</button><button class="menuitem" onclick="duplicateProduct('${sid}','${pid}')">⧉ Duplica</button><button class="menuitem" onclick="deleteProduct('${sid}','${pid}')">🗑 Elimina</button>`,null,false)}
function duplicateProduct(sid,pid){let s=supplier(sid),p=s.products.find(x=>x.id===pid),i=s.products.indexOf(p);s.products.splice(i+1,0,{...p,id:uuid(),name:p.name+' (copia)',qty:0});save();closeModal();render()}
function deleteProduct(sid,pid){let s=supplier(sid),p=s.products.find(x=>x.id===pid);if(confirm(`Eliminare ${p.name}?`)){s.products=s.products.filter(x=>x.id!==pid);save();closeModal();render()}}
let dragSupplierId=null,dragProdId=null;function dragStart(e){dragSupplierId=e.currentTarget.dataset.supplier;e.currentTarget.classList.add('dragging')}function dropSupplier(e,target){e.preventDefault();if(!dragSupplierId||dragSupplierId===target)return;let a=state.suppliers.findIndex(s=>s.id===dragSupplierId),b=state.suppliers.findIndex(s=>s.id===target),x=state.suppliers.splice(a,1)[0];if(a<b)b--;state.suppliers.splice(b,0,x);dragSupplierId=null;save();render()}
function dragProductStart(e,id){dragProdId=id;e.currentTarget.classList.add('dragging')}function dropProduct(e,target){e.preventDefault();let s=supplier(view.supplierId);if(!dragProdId||dragProdId===target)return;let a=s.products.findIndex(p=>p.id===dragProdId),b=s.products.findIndex(p=>p.id===target),x=s.products.splice(a,1)[0];if(a<b)b--;s.products.splice(b,0,x);dragProdId=null;save();render()}
function openDrawer(){let el=document.createElement('div');el.className='drawer-back';el.id='drawerBack';el.onclick=e=>{if(e.target===el)el.remove()};el.innerHTML=`<aside class="drawer"><h2>Ordini Fornitori</h2><p>PWA v1.4</p><button class="menuitem" onclick="closeDrawer();showHistory()">🕘 Storico ordini</button><button class="menuitem" onclick="closeDrawer();showStats()">▥ Spesa mensile</button><button class="menuitem" onclick="closeDrawer();showArchive()">▣ Fornitori archiviati (${state.suppliers.filter(s=>s.archived).length})</button><hr style="border:0;border-top:1px solid var(--line);margin:10px 0"><button class="menuitem" onclick="exportLists()">⇩ Esporta liste</button><button class="menuitem" onclick="exportFull()">⇩ Backup completo</button><button class="menuitem" onclick="$('#importFile').click()">⇧ Importa backup/liste</button><button class="menuitem" onclick="restoreInternal()">↶ Ripristina backup automatico</button><button class="menuitem" onclick="toggleTheme()">◐ Modalità chiara/scura</button></aside>`;document.body.appendChild(el)}function closeDrawer(){$('#drawerBack')?.remove()}
function toggleTheme(){setTheme(!document.documentElement.classList.contains('dark'));closeDrawer();render()}
function exportLists(){let x={format:'OrdiniFornitoriBackup',version:2,suppliers:state.suppliers.map(s=>({...s,products:s.products.map(p=>({...p,qty:0}))}))};downloadJson(x,'ordini-fornitori-liste.json')}
function exportFull(){downloadJson({...state,format:'OrdiniFornitoriFullBackup',schemaVersion:3,createdAt:Date.now()},'ordini-fornitori-backup-completo.json')}
function downloadJson(obj,name){let blob=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('#importFile').addEventListener('change',e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!Array.isArray(x.suppliers))throw 0;if(!confirm('Importare il file? I fornitori attuali verranno sostituiti.'))return;let full=Array.isArray(x.history);let n=normalize({...x,history:full?x.history:state.history});if(!full)n.suppliers.forEach(s=>s.products.forEach(p=>p.qty=0));state=n;save();closeDrawer();view.page='home';render();alert('Importazione completata.')}catch{alert('File non valido o non compatibile.')}};r.readAsText(f);e.target.value=''})
function restoreInternal(){let raw=localStorage.getItem(BACK);if(!raw)return alert('Nessun backup automatico disponibile.');if(confirm('Ripristinare il backup precedente?')){state=normalize(JSON.parse(raw));localStorage.setItem(KEY,raw);closeDrawer();render()}}
function showArchive(){closeDrawer();view.page='archive';render()}function archiveView(){let ar=state.suppliers.filter(s=>s.archived);app.innerHTML=topbar('Fornitori archiviati',`${ar.length} archiviati`,true)+`<main>${ar.length?ar.map(s=>`<section class="card"><div class="supplier-name">${esc(s.name)}</div><div class="meta">${s.products.length} prodotti</div><div class="actions"><button class="btn primary flex" onclick="restoreSupplier('${s.id}')">Ripristina</button><button class="btn danger" onclick="hardDeleteSupplier('${s.id}')">Elimina</button></div></section>`).join(''):'<div class="empty">Archivio vuoto.</div>'}</main>`}function restoreSupplier(id){supplier(id).archived=false;save();render()}function hardDeleteSupplier(id){let s=supplier(id);if(confirm(`Eliminare definitivamente ${s.name}? Lo storico resterà disponibile.`)){state.suppliers=state.suppliers.filter(x=>x.id!==id);save();render()}}
function recordOrder(s){if(!itemCount(s))return;state.history.unshift({id:uuid(),supplierId:s.id,supplierName:s.name,dateMillis:Date.now(),total:total(s),items:s.products.filter(p=>p.qty>0).map(p=>({productId:p.id,name:p.name,price:p.price,qty:p.qty,unit:p.unit}))});save()}
function messageFor(s){let lines=[`*${s.name}*`,''];s.products.filter(p=>p.qty>0).forEach(p=>lines.push(`• ${p.name} — ${p.qty} ${p.unit} × ${euro(p.price)} = ${euro(p.qty*p.price)}`));lines.push('',`*TOTALE: ${euro(total(s))}*`);return lines.join('\n')}
let shareQueue=[],shareIndex=0;function startShare(){shareQueue=state.suppliers.filter(s=>!s.archived&&itemCount(s)>0).map(s=>s.id);shareIndex=0;shareStep()}function shareOne(id){shareQueue=[id];shareIndex=0;shareStep()}
function shareStep(){if(shareIndex>=shareQueue.length){alert('Ordini completati.');view.page='home';render();return}let s=supplier(shareQueue[shareIndex]);modal(`<h3>${esc(s.name)}</h3><div class="notice">Messaggio ${shareIndex+1} di ${shareQueue.length}. Verrà inviato separatamente dagli altri fornitori.</div><div class="card" style="white-space:pre-wrap;font-size:13px">${esc(messageFor(s))}</div><div class="actions"><button class="btn primary flex" onclick="openWhatsApp('${s.id}')">Apri WhatsApp</button></div><div class="meta" style="margin-top:12px">Dopo l’invio torna qui e conferma. Solo allora le quantità verranno azzerate.</div>`,null,false)}
function openWhatsApp(id){let s=supplier(id);location.href='https://wa.me/?text='+encodeURIComponent(messageFor(s));setTimeout(()=>confirmSent(id),800)}
function confirmSent(id){let s=supplier(id);modal(`<h3>Ordine inviato?</h3><p>Hai inviato il messaggio a <b>${esc(s.name)}</b>?</p><div class="modal-actions"><button class="btn secondary" onclick="shareStep()">No / Riprova</button><button class="btn primary" onclick="markSent('${id}')">Sì, inviato</button></div>`,null,false)}
function markSent(id){let s=supplier(id);recordOrder(s);s.products.forEach(p=>p.qty=0);save();closeModal();shareIndex++;shareStep()}
function resetAll(){if(confirm('Azzerare tutte le quantità dell’ordine corrente?')){state.suppliers.forEach(s=>s.products.forEach(p=>p.qty=0));save();render()}}
function showHistory(){closeDrawer();view.page='history';render()}function historyView(){let months=[...new Set(state.history.map(h=>{let d=new Date(h.dateMillis);return `${d.getFullYear()}-${d.getMonth()}`}))];let names=[...new Set(state.history.map(h=>h.supplierName))];let hist=state.history.filter(h=>{let d=new Date(h.dateMillis),mk=`${d.getFullYear()}-${d.getMonth()}`;return(view.histMonth==='all'||view.histMonth===mk)&&(view.histSupplier==='all'||view.histSupplier===h.supplierName)});let now=new Date(),cur=monthTotal(now.getFullYear(),now.getMonth()),prevD=new Date(now.getFullYear(),now.getMonth()-1,1),prev=monthTotal(prevD.getFullYear(),prevD.getMonth()),delta=prev?((cur-prev)/prev*100):null;let curOrders=monthOrders(now.getFullYear(),now.getMonth()),counts={};curOrders.forEach(h=>counts[h.supplierName]=(counts[h.supplierName]||0)+1);let top=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0]?.[0]||'—';app.innerHTML=topbar('Storico ordini','Cronologia e filtri',true)+`<main><div class="stats-grid"><div class="stat"><div class="l">Speso questo mese</div><div class="v">${euro(cur)}</div></div><div class="stat"><div class="l">Fornitore più usato</div><div class="v" style="font-size:15px">${esc(top)}</div></div><div class="stat"><div class="l">Vs mese precedente</div><div class="v">${delta===null?'—':(delta>=0?'+':'')+delta.toFixed(0)+'%'}</div></div></div><div class="filters"><select onchange="view.histMonth=this.value;render()"><option value="all">Tutti i mesi</option>${months.map(k=>{let [y,m]=k.split('-').map(Number);return `<option value="${k}" ${view.histMonth===k?'selected':''}>${monthLabel(y,m)}</option>`}).join('')}</select><select onchange="view.histSupplier=this.value;render()"><option value="all">Tutti i fornitori</option>${names.map(n=>`<option ${view.histSupplier===n?'selected':''}>${esc(n)}</option>`).join('')}</select></div>${hist.length?hist.map(h=>`<section class="card history-card"><div class="date">${new Date(h.dateMillis).toLocaleString('it-IT',{dateStyle:'medium',timeStyle:'short'})}</div><div class="name">${esc(h.supplierName)}</div><div class="total">${euro(h.total)}</div><div class="items">${h.items.map(i=>`${esc(i.name)} · ${i.qty} ${esc(i.unit)} · ${euro(i.price*i.qty)}`).join('<br>')}</div><div class="actions"><button class="btn secondary flex" onclick="reopenOrder('${h.id}')">Riapri ordine</button></div></section>`).join(''):'<div class="empty">Nessun ordine per questi filtri.</div>'}</main>`}
function reopenOrder(id){let h=state.history.find(x=>x.id===id),s=supplier(h.supplierId)||state.suppliers.find(x=>x.name.toLowerCase()===h.supplierName.toLowerCase());if(!s){s={id:h.supplierId||uuid(),name:h.supplierName,archived:false,products:[]};state.suppliers.push(s)}s.archived=false;s.products.forEach(p=>p.qty=0);h.items.forEach(i=>{let p=s.products.find(p=>(i.productId&&p.id===i.productId)||p.name.toLowerCase()===i.name.toLowerCase());if(!p){p={id:i.productId||uuid(),name:i.name,price:i.price,qty:0,unit:i.unit||'pz'};s.products.push(p)}p.qty=i.qty});save();view.page='supplier';view.supplierId=s.id;render()}
function showStats(){closeDrawer();view.page='stats';render()}function statsView(){let d=view.statsDate,y=d.getFullYear(),m=d.getMonth(),orders=monthOrders(y,m),tot=orders.reduce((a,h)=>a+h.total,0),pd=new Date(y,m-1,1),prev=monthTotal(pd.getFullYear(),pd.getMonth()),map={};orders.forEach(h=>map[h.supplierName]=(map[h.supplierName]||0)+h.total);let max=Math.max(1,...Object.values(map));app.innerHTML=topbar('Spesa mensile',monthLabel(y,m),true)+`<main><div class="actions" style="margin:0 0 12px"><button class="btn secondary flex" onclick="shiftMonth(-1)">‹ Mese precedente</button><button class="btn secondary flex" onclick="shiftMonth(1)">Mese successivo ›</button></div><div class="stats-grid"><div class="stat"><div class="l">Totale</div><div class="v">${euro(tot)}</div></div><div class="stat"><div class="l">Ordini</div><div class="v">${orders.length}</div></div><div class="stat"><div class="l">Vs mese precedente</div><div class="v">${prev?((tot-prev)/prev*100>=0?'+':'')+((tot-prev)/prev*100).toFixed(0)+'%':'—'}</div></div></div><div class="chart"><b>Spesa per fornitore</b>${Object.keys(map).length?Object.entries(map).sort((a,b)=>b[1]-a[1]).map(([n,v])=>`<div class="barrow"><div class="barlabel">${esc(n)}</div><div class="bartrack"><div class="bar" style="width:${v/max*100}%"></div></div><div class="barvalue">${euro(v)}</div></div>`).join(''):'<div class="empty">Nessun ordine registrato.</div>'}</div></main>`}function shiftMonth(n){view.statsDate=new Date(view.statsDate.getFullYear(),view.statsDate.getMonth()+n,1);render()}
function modal(html,onSave,showActions=true){closeModal();let b=document.createElement('div');b.className='modal-back';b.id='modalBack';b.onclick=e=>{if(e.target===b)closeModal()};b.innerHTML=`<div class="modal">${html}${showActions&&onSave?`<div class="modal-actions"><button class="btn secondary" onclick="closeModal()">Annulla</button><button class="btn primary" id="modalSave">Salva</button></div>`:''}</div>`;document.body.appendChild(b);if(showActions&&onSave)$('#modalSave').onclick=onSave}function closeModal(){$('#modalBack')?.remove()}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
render();
