
const KEY='ordini_fornitori_pwa_v14', BACK='ordini_fornitori_pwa_backup', THEME='ordini_theme';
const $=s=>document.querySelector(s); const app=$('#app'); const uuid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const euro=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(n)||0);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=load(), view={page:'home', supplierId:null, histMonth:'all',histSupplier:'all', statsDate:new Date()};
function fresh(){const cid=uuid();return {format:'OrdiniFornitoriFullBackup',schemaVersion:7,createdAt:Date.now(),categories:[{id:cid,name:'Generale'}],suppliers:[{id:uuid(),name:'Fornitore esempio',archived:false,categoryId:cid,products:[{id:uuid(),name:'Prodotto A',price:2.5,qty:0,unit:'pz',minQty:1,qtyStep:1,note:''},{id:uuid(),name:'Prodotto B',price:4.9,qty:0,unit:'pz',minQty:1,qtyStep:1,note:''}]}],history:[]}}
function normalize(x){
  if(!x||!Array.isArray(x.suppliers)) return fresh();
  x.history=Array.isArray(x.history)?x.history:[];
  x.categories=Array.isArray(x.categories)?x.categories.filter(c=>c&&String(c.name||'').trim()).map(c=>({id:c.id||uuid(),name:String(c.name).trim()})):[];
  if(!x.categories.length)x.categories=[{id:uuid(),name:'Generale'}];
  const valid=new Set(x.categories.map(c=>c.id)),fallback=x.categories[0].id;
  x.suppliers=x.suppliers.map(s=>({id:s.id||uuid(),name:s.name||'Fornitore',archived:!!s.archived,categoryId:(!s.archived&&valid.has(s.categoryId))?s.categoryId:(s.archived?'':fallback),products:(s.products||[]).map(p=>({id:p.id||uuid(),name:p.name||'Prodotto',price:Math.max(0,+p.price||0),qty:Math.max(0,parseInt(p.qty)||0),unit:(p.unit||'pz').trim()||'pz',minQty:Math.max(1,parseInt(p.minQty)||1),qtyStep:Math.max(1,parseInt(p.qtyStep)||1),note:String(p.note||'').trim()}))}));
  x.history=x.history.map(h=>({id:h.id||uuid(),supplierId:h.supplierId||'',supplierName:h.supplierName||'Fornitore',dateMillis:+h.dateMillis||Date.now(),total:Math.max(0,+h.total||0),items:(h.items||[]).map(i=>({productId:i.productId||'',name:i.name||'Prodotto',price:Math.max(0,+i.price||0),qty:Math.max(0,parseInt(i.qty)||0),unit:i.unit||'pz',minQty:Math.max(1,parseInt(i.minQty)||1),qtyStep:Math.max(1,parseInt(i.qtyStep)||1),note:String(i.note||'').trim()}))}));
  x.schemaVersion=7; return x;
}
function load(){try{return normalize(JSON.parse(localStorage.getItem(KEY)))}catch{return fresh()}}
function save(){state.createdAt=Date.now(); try{const old=localStorage.getItem(KEY); if(old)localStorage.setItem(BACK,old); localStorage.setItem(KEY,JSON.stringify(state));}catch{} }
function supplier(id){return state.suppliers.find(s=>s.id===id)}
function total(s){return s.products.reduce((a,p)=>a+p.price*p.qty,0)} function itemCount(s){return s.products.reduce((a,p)=>a+p.qty,0)} function selectedCount(s){return s.products.filter(p=>p.qty>0).length}
function monthTotal(y,m){return state.history.filter(h=>{let d=new Date(h.dateMillis);return d.getFullYear()==y&&d.getMonth()==m}).reduce((a,h)=>a+h.total,0)}
function monthOrders(y,m){return state.history.filter(h=>{let d=new Date(h.dateMillis);return d.getFullYear()==y&&d.getMonth()==m})}
function monthLabel(y,m){return new Date(y,m,1).toLocaleDateString('it-IT',{month:'long',year:'numeric'})}
function setTheme(dark){document.documentElement.classList.toggle('dark',dark);localStorage.setItem(THEME,dark?'dark':'light')}
setTheme(localStorage.getItem(THEME)==='dark');
function topbar(title,sub='',back=false){return `<header class="topbar"><button class="iconbtn" onclick="${back?'goHome()':'openDrawer()'}">${back?'‹':'☰'}</button><div class="top-title"><h1>${esc(title)}</h1>${sub?`<small>${esc(sub)}</small>`:''}</div></header>`}
function render(){ if(view.page==='home')home(); else if(view.page==='supplier')supplierView(); else if(view.page==='history')historyView(); else if(view.page==='stats')statsView(); else if(view.page==='archive')archiveView(); }
function home(){let now=new Date(), mt=monthTotal(now.getFullYear(),now.getMonth());let active=state.suppliers.filter(s=>!s.archived); app.innerHTML=topbar('Ordini Fornitori',`Speso a ${monthLabel(now.getFullYear(),now.getMonth())}: ${euro(mt)}`)+`<main><div class="hero"><div class="row"><div><div class="label">Ordine corrente</div><div class="money">${euro(active.reduce((a,s)=>a+total(s),0))}</div><div class="label">${active.reduce((a,s)=>a+itemCount(s),0)} unità selezionate</div></div><button onclick="showStats()">Statistiche</button></div></div><div class="section-head"><h2>Fornitori</h2><button onclick="editSupplier()">+ Fornitore</button></div><div class="supplier-grid">${active.length?active.map(s=>`<section class="card" draggable="true" data-supplier="${s.id}" ondragstart="dragStart(event)" ondragover="event.preventDefault()" ondrop="dropSupplier(event,'${s.id}')"><div class="supplier-head"><span class="handle">≡</span><div class="supplier-info"><div class="supplier-name">${esc(s.name)}</div><div class="meta">${selectedCount(s)} prodotti selezionati · ${itemCount(s)} unità</div><div class="amount">${euro(total(s))}</div></div><button class="dots" onclick="supplierMenu('${s.id}')">⋮</button></div><div class="actions"><button class="btn primary flex" onclick="openSupplier('${s.id}')">Apri</button></div></section>`).join(''):'<div class="empty">Nessun fornitore attivo.</div>'}</div></main>${orderBottom(active)}`; }
function orderBottom(active){let used=active.filter(s=>itemCount(s)>0);if(!used.length)return '';return `<div class="bottom-summary"><div class="bottom-inner"><div class="grow"><small>${used.length} fornitor${used.length===1?'e':'i'} nell’ordine</small><strong>${euro(used.reduce((a,s)=>a+total(s),0))}</strong></div><button onclick="startShare()">WhatsApp</button></div></div>`}
function openSupplier(id){view={...view,page:'supplier',supplierId:id};render()} function goHome(){view.page='home';view.supplierId=null;render()}
function supplierView(){let s=supplier(view.supplierId);if(!s)return goHome();app.innerHTML=topbar(s.name,`${s.products.length} prodotti`,true)+`<main><div class="section-head"><h2>Prodotti</h2><button onclick="editProduct('${s.id}')">+ Prodotto</button></div>${s.products.length?s.products.map(p=>`<section class="card product ${p.qty>0?'selected':''}" draggable="true" ondragstart="dragProductStart(event,'${p.id}')" ondragover="event.preventDefault()" ondrop="dropProduct(event,'${p.id}')"><div class="prod-top"><span class="handle">≡</span><div class="prod-main"><div class="prod-name">${esc(p.name)}</div><div class="prod-sub">${euro(p.price)} · ${esc(p.unit)} · minimo ${p.minQty} · incremento ${p.qtyStep}</div>${p.note?`<div class="prod-note">Nota: ${esc(p.note)}</div>`:''}</div><button class="dots" onclick="productMenu('${s.id}','${p.id}')">⋮</button></div><div class="stepper"><button onclick="changeQty('${s.id}','${p.id}',-1)">−</button><div><div class="qty">${p.qty}</div><div class="qtylabel">Quantità</div></div><button class="plus" onclick="changeQty('${s.id}','${p.id}',1)">+</button></div><div class="product-foot"><span>Minimo ${p.minQty} · +${p.qtyStep} ${esc(p.unit)}</span><strong>${euro(p.price*p.qty)}</strong></div></section>`).join(''):'<div class="empty">Nessun prodotto.</div>'}</main><div class="bottom-summary"><div class="bottom-inner"><div class="grow"><small>${itemCount(s)} unità</small><strong>${euro(total(s))}</strong></div><button onclick="shareOne('${s.id}')">WhatsApp</button></div></div>`}
function changeQty(sid,pid,d){let p=supplier(sid).products.find(x=>x.id===pid);if(d>0)p.qty=p.qty===0?p.minQty:p.qty+p.qtyStep;else if(d<0&&p.qty>0)p.qty=p.qty<=p.minQty?0:Math.max(p.minQty,p.qty-p.qtyStep);save();render()}
function editSupplier(id=null){let s=id?supplier(id):null;modal(`<h3>${s?'Modifica':'Nuovo'} fornitore</h3><div class="field"><label>Nome</label><input id="mname" value="${s?esc(s.name):''}" placeholder="Nome fornitore"></div>`,()=>{let n=$('#mname').value.trim();if(!n)return;if(s)s.name=n;else state.suppliers.push({id:uuid(),name:n,archived:false,products:[]});save();closeModal();render()})}
function editProduct(sid,pid=null){let s=supplier(sid),p=pid?s.products.find(x=>x.id===pid):null;modal(`<h3>${p?'Modifica':'Nuovo'} prodotto</h3><div class="field"><label>Nome</label><input id="pname" value="${p?esc(p.name):''}"></div><div class="field"><label>Prezzo</label><input id="pprice" type="number" step="0.01" min="0" value="${p?p.price:''}"></div><div class="field"><label>Unità di misura</label><input id="punit" value="${p?esc(p.unit):'pz'}" placeholder="pz, casse, kg..."></div><div class="field"><label>Quantità minima ordinabile</label><input id="pmin" type="number" step="1" min="1" value="${p?p.minQty:1}"></div><div class="field"><label>Incremento quantità</label><input id="pstep" type="number" step="1" min="1" value="${p?p.qtyStep:1}"><small>Es.: minimo 6 e incremento 2 → 0, 6, 8, 10...</small></div><div class="field"><label>Nota prodotto (facoltativa)</label><textarea id="pnote" rows="3" placeholder="Es. Se non disponibile non sostituire">${p?esc(p.note):''}</textarea></div>`,()=>{let n=$('#pname').value.trim(),pr=Math.max(0,+$('#pprice').value||0),u=$('#punit').value.trim()||'pz',mq=Math.max(1,parseInt($('#pmin').value)||1),step=Math.max(1,parseInt($('#pstep').value)||1),note=$('#pnote').value.trim();if(!n)return;if(p){p.name=n;p.price=pr;p.unit=u;p.minQty=mq;p.qtyStep=step;p.note=note;if(p.qty>0&&p.qty<mq)p.qty=mq}else s.products.push({id:uuid(),name:n,price:pr,qty:0,unit:u,minQty:mq,qtyStep:step,note});save();closeModal();render()})}
function supplierMenu(id){let s=supplier(id);modal(`<h3>${esc(s.name)}</h3><button class="menuitem" onclick="closeModal();editSupplier('${id}')">✎ Modifica nome</button><button class="menuitem" onclick="duplicateSupplier('${id}')">⧉ Duplica fornitore</button><button class="menuitem" onclick="archiveSupplier('${id}')">▣ Archivia fornitore</button>`,null,false)}
function duplicateSupplier(id){let s=supplier(id),i=state.suppliers.indexOf(s);state.suppliers.splice(i+1,0,{id:uuid(),name:s.name+' (copia)',archived:false,products:s.products.map(p=>({...p,id:uuid(),qty:0}))});save();closeModal();render()}
function archiveSupplier(id){let s=supplier(id);if(confirm(`Archiviare ${s.name}?`)){s.archived=true;s.products.forEach(p=>p.qty=0);save();closeModal();render()}}
function productMenu(sid,pid){let s=supplier(sid),p=s.products.find(x=>x.id===pid);modal(`<h3>${esc(p.name)}</h3><button class="menuitem" onclick="closeModal();editProduct('${sid}','${pid}')">✎ Modifica</button><button class="menuitem" onclick="duplicateProduct('${sid}','${pid}')">⧉ Duplica</button><button class="menuitem" onclick="deleteProduct('${sid}','${pid}')">🗑 Elimina</button>`,null,false)}
function duplicateProduct(sid,pid){let s=supplier(sid),p=s.products.find(x=>x.id===pid),i=s.products.indexOf(p);s.products.splice(i+1,0,{...p,id:uuid(),name:p.name+' (copia)',qty:0});save();closeModal();render()}
function deleteProduct(sid,pid){let s=supplier(sid),p=s.products.find(x=>x.id===pid);if(confirm(`Eliminare ${p.name}?`)){s.products=s.products.filter(x=>x.id!==pid);save();closeModal();render()}}
let dragSupplierId=null,dragProdId=null;function dragStart(e){dragSupplierId=e.currentTarget.dataset.supplier;e.currentTarget.classList.add('dragging')}function dropSupplier(e,target){e.preventDefault();if(!dragSupplierId||dragSupplierId===target)return;let a=state.suppliers.findIndex(s=>s.id===dragSupplierId),b=state.suppliers.findIndex(s=>s.id===target),x=state.suppliers.splice(a,1)[0];if(a<b)b--;state.suppliers.splice(b,0,x);dragSupplierId=null;save();render()}
function dragProductStart(e,id){dragProdId=id;e.currentTarget.classList.add('dragging')}function dropProduct(e,target){e.preventDefault();let s=supplier(view.supplierId);if(!dragProdId||dragProdId===target)return;let a=s.products.findIndex(p=>p.id===dragProdId),b=s.products.findIndex(p=>p.id===target),x=s.products.splice(a,1)[0];if(a<b)b--;s.products.splice(b,0,x);dragProdId=null;save();render()}
function openDrawer(){let el=document.createElement('div');el.className='drawer-back';el.id='drawerBack';el.onclick=e=>{if(e.target===el)el.remove()};el.innerHTML=`<aside class="drawer"><h2>Ordini Fornitori</h2><p>PWA v1.7.3</p><button class="menuitem" onclick="closeDrawer();showHistory()">🕘 Storico ordini</button><button class="menuitem" onclick="closeDrawer();showStats()">▥ Spesa mensile</button><button class="menuitem" onclick="closeDrawer();showArchive()">▣ Fornitori archiviati (${state.suppliers.filter(s=>s.archived).length})</button><hr style="border:0;border-top:1px solid var(--line);margin:10px 0"><button class="menuitem" onclick="exportLists()">⇩ Esporta liste</button><button class="menuitem" onclick="exportFull()">⇩ Backup completo</button><button class="menuitem" onclick="$('#importFile').click()">⇧ Importa backup/liste</button><button class="menuitem" onclick="restoreInternal()">↶ Ripristina backup automatico</button><button class="menuitem" onclick="toggleTheme()">◐ Modalità chiara/scura</button></aside>`;document.body.appendChild(el)}function closeDrawer(){$('#drawerBack')?.remove()}
function toggleTheme(){setTheme(!document.documentElement.classList.contains('dark'));closeDrawer();render()}
function exportLists(){let x={format:'OrdiniFornitoriBackup',version:3,suppliers:state.suppliers.map(s=>({...s,products:s.products.map(p=>({...p,qty:0}))}))};downloadJson(x,'ordini-fornitori-liste.json')}
function exportFull(){downloadJson({...state,format:'OrdiniFornitoriFullBackup',schemaVersion:5,createdAt:Date.now()},'ordini-fornitori-backup-completo.json')}
function downloadJson(obj,name){let blob=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('#importFile').addEventListener('change',e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!Array.isArray(x.suppliers))throw 0;if(!confirm('Importare il file? I dati compatibili presenti verranno sostituiti.'))return;let full=Array.isArray(x.history);let n=normalize({...x,history:full?x.history:state.history});if(!full)n.suppliers.forEach(s=>s.products.forEach(p=>p.qty=0));state=n;if(x.ui){if(x.ui.theme)localStorage.setItem(THEME,x.ui.theme);if(x.ui.accent)localStorage.setItem('ordini_accent',x.ui.accent);}save();closeDrawer();view.page='home';applyAccent(localStorage.getItem('ordini_accent')||'blue');setTheme(localStorage.getItem(THEME)==='dark');render();alert('Importazione completata.')}catch{alert('File non valido o non compatibile.')}};r.readAsText(f);e.target.value=''})
function restoreInternal(){let raw=localStorage.getItem(BACK);if(!raw)return alert('Nessun backup automatico disponibile.');if(confirm('Ripristinare il backup precedente?')){state=normalize(JSON.parse(raw));localStorage.setItem(KEY,raw);closeDrawer();render()}}
function showArchive(){closeDrawer();view.page='archive';render()}function archiveView(){let ar=state.suppliers.filter(s=>s.archived);app.innerHTML=topbar('Fornitori archiviati',`${ar.length} archiviati`,true)+`<main>${ar.length?ar.map(s=>`<section class="card"><div class="supplier-name">${esc(s.name)}</div><div class="meta">${s.products.length} prodotti</div><div class="actions"><button class="btn primary flex" onclick="restoreSupplier('${s.id}')">Ripristina</button><button class="btn danger" onclick="hardDeleteSupplier('${s.id}')">Elimina</button></div></section>`).join(''):'<div class="empty">Archivio vuoto.</div>'}</main>`}function restoreSupplier(id){supplier(id).archived=false;save();render()}function hardDeleteSupplier(id){let s=supplier(id);if(confirm(`Eliminare definitivamente ${s.name}? Lo storico resterà disponibile.`)){state.suppliers=state.suppliers.filter(x=>x.id!==id);save();render()}}
function recordOrder(s){if(!itemCount(s))return;state.history.unshift({id:uuid(),supplierId:s.id,supplierName:s.name,dateMillis:Date.now(),total:total(s),items:s.products.filter(p=>p.qty>0).map(p=>({productId:p.id,name:p.name,price:p.price,qty:p.qty,unit:p.unit,minQty:p.minQty,qtyStep:p.qtyStep,note:p.note||''}))});save()}
function messageFor(s){let lines=[`ORDINE - ${s.name.toUpperCase()}`,''];s.products.filter(p=>p.qty>0).forEach(p=>{lines.push(`• ${p.name} — ${p.qty} ${p.unit}`);if(p.note)lines.push(`  Nota: ${p.note}`)});lines.push('',`TOTALE ${s.name.toUpperCase()}: ${euro(total(s))}`);return lines.join('\n')}
let shareQueue=[],shareIndex=0;function startShare(){shareQueue=state.suppliers.filter(s=>!s.archived&&itemCount(s)>0).map(s=>s.id);shareIndex=0;shareStep()}function shareOne(id){shareQueue=[id];shareIndex=0;shareStep()}
function shareStep(){if(shareIndex>=shareQueue.length){alert('Ordini completati.');view.page='home';render();return}let s=supplier(shareQueue[shareIndex]);modal(`<h3>${esc(s.name)}</h3><div class="notice">Messaggio ${shareIndex+1} di ${shareQueue.length}. Verrà inviato separatamente dagli altri fornitori.</div><div class="card" style="white-space:pre-wrap;font-size:13px">${esc(messageFor(s))}</div><div class="actions"><button class="btn primary flex" onclick="openWhatsApp('${s.id}')">Apri WhatsApp</button></div><div class="meta" style="margin-top:12px">Dopo l’invio torna qui e conferma. Solo allora quantità e note dei prodotti inviati verranno azzerate.</div>`,null,false)}
function openWhatsApp(id){let s=supplier(id);location.href='https://wa.me/?text='+encodeURIComponent(messageFor(s));setTimeout(()=>confirmSent(id),800)}
function confirmSent(id){let s=supplier(id);modal(`<h3>Ordine inviato?</h3><p>Hai inviato il messaggio a <b>${esc(s.name)}</b>?</p><div class="modal-actions"><button class="btn secondary" onclick="shareStep()">No / Riprova</button><button class="btn primary" onclick="markSent('${id}')">Sì, inviato</button></div>`,null,false)}
function markSent(id){let s=supplier(id);recordOrder(s);s.products.forEach(p=>{if(p.qty>0)p.note='';p.qty=0});save();closeModal();shareIndex++;shareStep()}
function resetAll(){if(confirm('Azzerare tutte le quantità dell’ordine corrente?')){state.suppliers.forEach(s=>s.products.forEach(p=>p.qty=0));save();render()}}
function showHistory(){closeDrawer();view.page='history';render()}function historyView(){let months=[...new Set(state.history.map(h=>{let d=new Date(h.dateMillis);return `${d.getFullYear()}-${d.getMonth()}`}))];let names=[...new Set(state.history.map(h=>h.supplierName))];let hist=state.history.filter(h=>{let d=new Date(h.dateMillis),mk=`${d.getFullYear()}-${d.getMonth()}`;return(view.histMonth==='all'||view.histMonth===mk)&&(view.histSupplier==='all'||view.histSupplier===h.supplierName)});let now=new Date(),cur=monthTotal(now.getFullYear(),now.getMonth()),prevD=new Date(now.getFullYear(),now.getMonth()-1,1),prev=monthTotal(prevD.getFullYear(),prevD.getMonth()),delta=prev?((cur-prev)/prev*100):null;let curOrders=monthOrders(now.getFullYear(),now.getMonth()),counts={};curOrders.forEach(h=>counts[h.supplierName]=(counts[h.supplierName]||0)+1);let top=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0]?.[0]||'—';app.innerHTML=topbar('Storico ordini','Cronologia e filtri',true)+`<main><div class="stats-grid"><div class="stat"><div class="l">Speso questo mese</div><div class="v">${euro(cur)}</div></div><div class="stat"><div class="l">Fornitore più usato</div><div class="v" style="font-size:15px">${esc(top)}</div></div><div class="stat"><div class="l">Vs mese precedente</div><div class="v">${delta===null?'—':(delta>=0?'+':'')+delta.toFixed(0)+'%'}</div></div></div><div class="filters"><select onchange="view.histMonth=this.value;render()"><option value="all">Tutti i mesi</option>${months.map(k=>{let [y,m]=k.split('-').map(Number);return `<option value="${k}" ${view.histMonth===k?'selected':''}>${monthLabel(y,m)}</option>`}).join('')}</select><select onchange="view.histSupplier=this.value;render()"><option value="all">Tutti i fornitori</option>${names.map(n=>`<option ${view.histSupplier===n?'selected':''}>${esc(n)}</option>`).join('')}</select></div>${hist.length?hist.map(h=>`<section class="card history-card"><div class="date">${new Date(h.dateMillis).toLocaleString('it-IT',{dateStyle:'medium',timeStyle:'short'})}</div><div class="name">${esc(h.supplierName)}</div><div class="total">${euro(h.total)}</div><div class="items">${h.items.map(i=>`${esc(i.name)} · ${i.qty} ${esc(i.unit)} · ${euro(i.price*i.qty)}${i.note?`<br><span class=\"hist-note\">Nota: ${esc(i.note)}</span>`:''}`).join('<br>')}</div><div class="actions"><button class="btn secondary flex" onclick="reopenOrder('${h.id}')">Riapri ordine</button></div></section>`).join(''):'<div class="empty">Nessun ordine per questi filtri.</div>'}</main>`}
function reopenOrder(id){let h=state.history.find(x=>x.id===id),s=supplier(h.supplierId)||state.suppliers.find(x=>x.name.toLowerCase()===h.supplierName.toLowerCase());if(!s){s={id:h.supplierId||uuid(),name:h.supplierName,archived:false,products:[]};state.suppliers.push(s)}s.archived=false;s.products.forEach(p=>p.qty=0);h.items.forEach(i=>{let p=s.products.find(p=>(i.productId&&p.id===i.productId)||p.name.toLowerCase()===i.name.toLowerCase());if(!p){p={id:i.productId||uuid(),name:i.name,price:i.price,qty:0,unit:i.unit||'pz',minQty:i.minQty||1,qtyStep:i.qtyStep||1,note:i.note||''};s.products.push(p)}p.qty=i.qty});save();view.page='supplier';view.supplierId=s.id;render()}
function showStats(){closeDrawer();view.page='stats';render()}function statsView(){let d=view.statsDate,y=d.getFullYear(),m=d.getMonth(),orders=monthOrders(y,m),tot=orders.reduce((a,h)=>a+h.total,0),pd=new Date(y,m-1,1),prev=monthTotal(pd.getFullYear(),pd.getMonth()),map={};orders.forEach(h=>map[h.supplierName]=(map[h.supplierName]||0)+h.total);let max=Math.max(1,...Object.values(map));app.innerHTML=topbar('Spesa mensile',monthLabel(y,m),true)+`<main><div class="actions" style="margin:0 0 12px"><button class="btn secondary flex" onclick="shiftMonth(-1)">‹ Mese precedente</button><button class="btn secondary flex" onclick="shiftMonth(1)">Mese successivo ›</button></div><div class="stats-grid"><div class="stat"><div class="l">Totale</div><div class="v">${euro(tot)}</div></div><div class="stat"><div class="l">Ordini</div><div class="v">${orders.length}</div></div><div class="stat"><div class="l">Vs mese precedente</div><div class="v">${prev?((tot-prev)/prev*100>=0?'+':'')+((tot-prev)/prev*100).toFixed(0)+'%':'—'}</div></div></div><div class="chart"><b>Spesa per fornitore</b>${Object.keys(map).length?Object.entries(map).sort((a,b)=>b[1]-a[1]).map(([n,v])=>`<div class="barrow"><div class="barlabel">${esc(n)}</div><div class="bartrack"><div class="bar" style="width:${v/max*100}%"></div></div><div class="barvalue">${euro(v)}</div></div>`).join(''):'<div class="empty">Nessun ordine registrato.</div>'}</div></main>`}function shiftMonth(n){view.statsDate=new Date(view.statsDate.getFullYear(),view.statsDate.getMonth()+n,1);render()}
function modal(html,onSave,showActions=true){closeModal();let b=document.createElement('div');b.className='modal-back';b.id='modalBack';b.onclick=e=>{if(e.target===b)closeModal()};b.innerHTML=`<div class="modal">${html}${showActions&&onSave?`<div class="modal-actions"><button class="btn secondary" onclick="closeModal()">Annulla</button><button class="btn primary" id="modalSave">Salva</button></div>`:''}</div>`;document.body.appendChild(b);if(showActions&&onSave)$('#modalSave').onclick=onSave}function closeModal(){$('#modalBack')?.remove()}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault()});
if('serviceWorker' in navigator){
  navigator.serviceWorker.register('sw.js?v=180',{updateViaCache:'none'}).then(reg=>{
    reg.update().catch(()=>{});
    setInterval(()=>reg.update().catch(()=>{}),60*60*1000);
  }).catch(()=>{});
  let reloading=false;
  navigator.serviceWorker.addEventListener('controllerchange',()=>{
    if(reloading)return; reloading=true; location.reload();
  });
}

// ===== v1.6.1 UI / storico / backup enhancements =====
let undoSnapshot = null;
function snapshotUndo(){ undoSnapshot = JSON.stringify(state); }
function undoLast(){ if(!undoSnapshot)return; state=normalize(JSON.parse(undoSnapshot)); undoSnapshot=null; save(); render(); }
function offerUndo(msg){ modal(`<h3>${esc(msg)}</h3><p class="meta">Puoi annullare immediatamente questa operazione.</p><div class="modal-actions"><button class="btn secondary" onclick="closeModal()">Chiudi</button><button class="btn primary" onclick="undoLast();closeModal()">Annulla azione</button></div>`,null,false); }

function applyAccent(name){
  const pal={blue:['#2563eb','#1d4ed8'],green:['#16a34a','#15803d'],purple:['#7c3aed','#6d28d9'],orange:['#ea580c','#c2410c'],red:['#e11d48','#be185d']};
  const key=pal[name]?name:'blue';
  document.documentElement.style.setProperty('--accent',pal[key][0]);
  document.documentElement.style.setProperty('--accent2',pal[key][1]);
  localStorage.setItem('ordini_accent',key);
}
function accentPicker(){
  const current=localStorage.getItem('ordini_accent')||'blue';
  const opts=[['blue','Blu'],['green','Verde'],['purple','Viola'],['orange','Arancione'],['red','Rosso']];
  modal(`<h3>Colore principale</h3><div class="accent-list">${opts.map(([k,l])=>`<button class="accent-choice ${current===k?'active':''}" onclick="applyAccent('${k}');closeModal();closeDrawer();render()"><span class="accent-dot accent-${k}"></span>${l}</button>`).join('')}</div>`,null,false);
}
function avgOrder(y,m){const o=monthOrders(y,m);return o.length?o.reduce((a,h)=>a+h.total,0)/o.length:0}
function topSpendSupplier(y,m){const map={};monthOrders(y,m).forEach(h=>map[h.supplierName]=(map[h.supplierName]||0)+h.total);return Object.entries(map).sort((a,b)=>b[1]-a[1])[0]?.[0]||'—'}
function weeklyTotals(y,m){const out=[0,0,0,0,0];monthOrders(y,m).forEach(h=>{const w=Math.min(4,Math.floor((new Date(h.dateMillis).getDate()-1)/7));out[w]+=h.total});return out}
function filteredHistoryNow(){return state.history.filter(h=>{let d=new Date(h.dateMillis),mk=`${d.getFullYear()}-${d.getMonth()}`;return(view.histMonth==='all'||view.histMonth===mk)&&(view.histSupplier==='all'||view.histSupplier===h.supplierName)})}
function deleteHistoryIds(ids,msg='Ordini eliminati'){if(!ids.length)return;snapshotUndo();state.history=state.history.filter(h=>!ids.includes(h.id));save();render();offerUndo(msg)}
function deleteHistoryRecord(id){if(confirm('Eliminare questo ordine?'))deleteHistoryIds([id],'Ordine eliminato')}
function deleteFilteredHistory(){const h=filteredHistoryNow();if(!h.length)return alert('Nessun ordine da eliminare.');if(confirm(`Eliminare ${h.length} ordini con i filtri attuali?`))deleteHistoryIds(h.map(x=>x.id),'Ordini filtrati eliminati')}
function clearAllHistory(){if(!state.history.length)return alert('Lo storico è già vuoto.');if(confirm('Azzerare tutto lo storico? Verranno azzerate anche le spese mensili registrate.'))deleteHistoryIds(state.history.map(x=>x.id),'Storico azzerato')}
function selectHistoryToDelete(){
  const h=filteredHistoryNow();if(!h.length)return alert('Nessun ordine con questi filtri.');
  modal(`<h3>Seleziona ordini da eliminare</h3><div class="select-orders">${h.map((o,i)=>`<label class="select-order"><input type="checkbox" value="${o.id}"><span><b>${esc(o.supplierName)}</b><small>${new Date(o.dateMillis).toLocaleString('it-IT')} · ${euro(o.total)}</small></span></label>`).join('')}</div><div class="modal-actions"><button class="btn secondary" onclick="closeModal()">Annulla</button><button class="btn danger" onclick="deleteCheckedHistory()">Elimina selezionati</button></div>`,null,false);
}
function deleteCheckedHistory(){const ids=[...document.querySelectorAll('.select-order input:checked')].map(x=>x.value);if(!ids.length)return alert('Seleziona almeno un ordine.');closeModal();deleteHistoryIds(ids,'Ordini selezionati eliminati')}
function deleteMonthOrders(y,m){const h=monthOrders(y,m);if(!h.length)return alert('Nessun ordine del mese da eliminare.');if(confirm(`Eliminare ${h.length} ordini di ${monthLabel(y,m)}?`))deleteHistoryIds(h.map(x=>x.id),'Spese del mese eliminate')}

function home(){let now=new Date(),mt=monthTotal(now.getFullYear(),now.getMonth()),active=state.suppliers.filter(s=>!s.archived);app.innerHTML=topbar('Ordini Fornitori',`Speso a ${monthLabel(now.getFullYear(),now.getMonth())}: ${euro(mt)}`)+`<main><div class="hero"><div class="row"><div><div class="label">Ordine corrente</div><div class="money">${euro(active.reduce((a,s)=>a+total(s),0))}</div><div class="label">${active.reduce((a,s)=>a+itemCount(s),0)} unità selezionate</div></div><button onclick="showStats()">Statistiche</button></div></div><div class="section-head"><h2>Fornitori</h2><button onclick="editSupplier()">+ Fornitore</button></div><div class="supplier-grid">${active.length?active.map(s=>`<section class="card compact" draggable="true" data-supplier="${s.id}" ondragstart="dragStart(event)" ondragover="event.preventDefault()" ondrop="dropSupplier(event,'${s.id}')"><div class="supplier-head"><span class="handle">≡</span><div class="supplier-info"><div class="supplier-name">${esc(s.name)}</div><div class="meta">${selectedCount(s)} prodotti selezionati · ${itemCount(s)} unità</div><div class="amount">${euro(total(s))}</div></div><button class="dots" onclick="supplierMenu('${s.id}')">⋮</button></div><div class="actions"><button class="btn primary flex" onclick="openSupplier('${s.id}')">Apri</button></div></section>`).join(''):'<div class="empty">Nessun fornitore attivo.</div>'}</div></main>${orderBottom(active)}`}

function supplierView(){let s=supplier(view.supplierId);if(!s)return goHome();app.innerHTML=topbar(s.name,`${s.products.length} prodotti`,true)+`<main><div class="section-head"><h2>Prodotti</h2><button onclick="editProduct('${s.id}')">+ Prodotto</button></div>${s.products.length?s.products.map(p=>`<section class="card product ${p.qty>0?'selected':''}" draggable="true" ondragstart="dragProductStart(event,'${p.id}')" ondragover="event.preventDefault()" ondrop="dropProduct(event,'${p.id}')"><div class="prod-top"><span class="handle">≡</span><div class="prod-main"><div class="prod-name">${esc(p.name)}</div><div class="prod-sub">${euro(p.price)} · ${esc(p.unit)} · minimo ${p.minQty} · incremento ${p.qtyStep}</div>${p.note?`<div class="prod-note">Nota: ${esc(p.note)}</div>`:''}</div><button class="dots" onclick="productMenu('${s.id}','${p.id}')">⋮</button></div><div class="stepper"><button onclick="changeQty('${s.id}','${p.id}',-1)">−</button><div><div class="qty">${p.qty}</div><div class="qtylabel">Quantità</div></div><button class="plus" onclick="changeQty('${s.id}','${p.id}',1)">+</button></div><div class="product-foot"><span>Minimo ${p.minQty} · +${p.qtyStep} ${esc(p.unit)}</span><strong>${euro(p.price*p.qty)}</strong></div></section>`).join(''):'<div class="empty">Nessun prodotto.</div>'}</main><div class="bottom-summary"><div class="bottom-inner"><div class="grow"><small>${itemCount(s)} unità</small><strong>${euro(total(s))}</strong></div><button onclick="shareOne('${s.id}')">WhatsApp</button></div></div>`}

function archiveSupplier(id){let s=supplier(id);if(confirm(`Archiviare ${s.name}?`)){snapshotUndo();s.archived=true;s.products.forEach(p=>p.qty=0);save();closeModal();render();offerUndo('Fornitore archiviato')}}
function deleteProduct(sid,pid){let s=supplier(sid),p=s.products.find(x=>x.id===pid);if(confirm(`Eliminare ${p.name}?`)){snapshotUndo();s.products=s.products.filter(x=>x.id!==pid);save();closeModal();render();offerUndo('Prodotto eliminato')}}
function hardDeleteSupplier(id){let s=supplier(id);if(confirm(`Eliminare definitivamente ${s.name}? Lo storico resterà disponibile.`)){snapshotUndo();state.suppliers=state.suppliers.filter(x=>x.id!==id);save();render();offerUndo('Fornitore eliminato')}}

function openDrawer(){let el=document.createElement('div');el.className='drawer-back';el.id='drawerBack';el.onclick=e=>{if(e.target===el)el.remove()};el.innerHTML=`<aside class="drawer"><h2>Ordini Fornitori</h2><p>PWA v1.7.3</p><button class="menuitem" onclick="closeDrawer();showHistory()">◷ <span>Storico ordini</span></button><button class="menuitem" onclick="closeDrawer();showStats()">▥ <span>Spesa mensile</span></button><button class="menuitem" onclick="closeDrawer();showArchive()">▣ <span>Fornitori archiviati (${state.suppliers.filter(s=>s.archived).length})</span></button><hr><button class="menuitem" onclick="exportLists()">⇧ <span>Esporta liste</span></button><button class="menuitem" onclick="exportFull()">⬆ <span>Esporta backup completo</span></button><button class="menuitem" onclick="$('#importFile').click()">⇩ <span>Importa backup/liste</span></button><button class="menuitem" onclick="restoreInternal()">↶ <span>Ripristina backup automatico</span></button><button class="menuitem" onclick="accentPicker()">◉ <span>Colore principale</span></button><button class="menuitem" onclick="toggleTheme()">◐ <span>Modalità chiara/scura</span></button></aside>`;document.body.appendChild(el)}
function exportFull(){downloadJson({...state,format:'OrdiniFornitoriFullBackup',schemaVersion:6,createdAt:Date.now(),ui:{theme:localStorage.getItem(THEME)||'light',accent:localStorage.getItem('ordini_accent')||'blue'}},'ordini-fornitori-backup-completo.json')}

function historyView(){let months=[...new Set(state.history.map(h=>{let d=new Date(h.dateMillis);return `${d.getFullYear()}-${d.getMonth()}`}))];let names=[...new Set(state.history.map(h=>h.supplierName))];let hist=filteredHistoryNow();let target=view.histMonth==='all'?new Date():new Date(Number(view.histMonth.split('-')[0]),Number(view.histMonth.split('-')[1]),1),y=target.getFullYear(),m=target.getMonth(),cur=monthTotal(y,m),pd=new Date(y,m-1,1),prev=monthTotal(pd.getFullYear(),pd.getMonth()),delta=prev?((cur-prev)/prev*100):null;app.innerHTML=topbar('Storico ordini','Cronologia e gestione',true)+`<main><div class="stats-grid four"><div class="stat"><div class="l">Totale mese</div><div class="v">${euro(cur)}</div></div><div class="stat"><div class="l">Media ordine</div><div class="v">${euro(avgOrder(y,m))}</div></div><div class="stat"><div class="l">Numero ordini</div><div class="v">${monthOrders(y,m).length}</div></div><div class="stat"><div class="l">Fornitore più costoso</div><div class="v smallv">${esc(topSpendSupplier(y,m))}</div></div></div><div class="compare-card"><span>Confronto mese precedente</span><b>${delta===null?'—':(delta>=0?'+':'')+delta.toFixed(1)+'%'}</b></div><div class="filters"><select onchange="view.histMonth=this.value;render()"><option value="all">Tutti i mesi</option>${months.map(k=>{let [yy,mm]=k.split('-').map(Number);return `<option value="${k}" ${view.histMonth===k?'selected':''}>${monthLabel(yy,mm)}</option>`}).join('')}</select><select onchange="view.histSupplier=this.value;render()"><option value="all">Tutti i fornitori</option>${names.map(n=>`<option ${view.histSupplier===n?'selected':''}>${esc(n)}</option>`).join('')}</select></div><div class="history-tools"><button class="btn primary" onclick="selectHistoryToDelete()">Seleziona ordini</button><button class="btn secondary" onclick="deleteFilteredHistory()">Elimina filtrati</button><button class="btn danger" onclick="clearAllHistory()">Azzera tutto</button></div>${hist.length?hist.map(h=>`<section class="card history-card compact"><div class="date">${new Date(h.dateMillis).toLocaleString('it-IT',{dateStyle:'medium',timeStyle:'short'})}</div><div class="name">${esc(h.supplierName)}</div><div class="total">${euro(h.total)}</div><div class="items">${h.items.map(i=>`${esc(i.name)} · ${i.qty} ${esc(i.unit)} · ${euro(i.price*i.qty)}${i.note?`<br><span class=\"hist-note\">Nota: ${esc(i.note)}</span>`:''}`).join('<br>')}</div><div class="actions"><button class="btn secondary flex" onclick="reopenOrder('${h.id}')">Riapri</button><button class="btn danger" onclick="deleteHistoryRecord('${h.id}')">Elimina</button></div></section>`).join(''):'<div class="empty">Nessun ordine per questi filtri.</div>'}</main>`}

function statsView(){let d=view.statsDate,y=d.getFullYear(),m=d.getMonth(),orders=monthOrders(y,m),tot=orders.reduce((a,h)=>a+h.total,0),pd=new Date(y,m-1,1),prev=monthTotal(pd.getFullYear(),pd.getMonth()),map={};orders.forEach(h=>map[h.supplierName]=(map[h.supplierName]||0)+h.total);let max=Math.max(1,...Object.values(map)),weeks=weeklyTotals(y,m),wmax=Math.max(1,...weeks);app.innerHTML=topbar('Spesa mensile',monthLabel(y,m),true)+`<main><div class="actions monthnav"><button class="btn secondary flex" onclick="shiftMonth(-1)">‹ Mese precedente</button><button class="btn secondary flex" onclick="shiftMonth(1)">Mese successivo ›</button></div><div class="stats-grid four"><div class="stat"><div class="l">Totale</div><div class="v">${euro(tot)}</div></div><div class="stat"><div class="l">Media ordine</div><div class="v">${euro(avgOrder(y,m))}</div></div><div class="stat"><div class="l">Ordini</div><div class="v">${orders.length}</div></div><div class="stat"><div class="l">Più costoso</div><div class="v smallv">${esc(topSpendSupplier(y,m))}</div></div></div><div class="compare-card"><span>Vs mese precedente</span><b>${prev?(((tot-prev)/prev*100)>=0?'+':'')+((tot-prev)/prev*100).toFixed(1)+'%':'—'}</b></div><button class="btn danger wide" onclick="deleteMonthOrders(${y},${m})">Elimina ordini del mese</button><div class="chart"><b>Spesa per fornitore</b>${Object.keys(map).length?Object.entries(map).sort((a,b)=>b[1]-a[1]).map(([n,v])=>`<div class="barrow"><div class="barlabel">${esc(n)}</div><div class="bartrack"><div class="bar" style="width:${v/max*100}%"></div></div><div class="barvalue">${euro(v)}</div></div>`).join(''):'<div class="empty">Nessun ordine registrato.</div>'}</div><div class="chart weekly"><b>Andamento settimanale</b>${weeks.map((v,i)=>`<div class="barrow"><div class="barlabel">Settimana ${i+1}</div><div class="bartrack"><div class="bar" style="width:${v/wmax*100}%"></div></div><div class="barvalue">${euro(v)}</div></div>`).join('')}</div></main>`}



// v1.7.1 - note rapide dalla card prodotto
function quickNote(sid,pid){
  const s=supplier(sid),p=s.products.find(x=>x.id===pid); if(!p)return;
  modal(`<h3>Nota · ${esc(p.name)}</h3><div class="field"><label>Nota prodotto</label><textarea id="quickNoteText" rows="4" placeholder="Scrivi una nota per questo prodotto...">${esc(p.note||'')}</textarea></div><div class="modal-actions"><button class="btn secondary" onclick="closeModal()">Annulla</button>${p.note?`<button class="btn danger" onclick="removeQuickNote('${sid}','${pid}')">Rimuovi</button>`:''}<button class="btn primary" onclick="saveQuickNote('${sid}','${pid}')">Salva</button></div>`,null,false);
  setTimeout(()=>$('#quickNoteText')?.focus(),50);
}
function saveQuickNote(sid,pid){const p=supplier(sid).products.find(x=>x.id===pid);p.note=$('#quickNoteText').value.trim();save();closeModal();render()}
function removeQuickNote(sid,pid){const p=supplier(sid).products.find(x=>x.id===pid);p.note='';save();closeModal();render()}
function supplierView(){
  let s=supplier(view.supplierId);if(!s)return goHome();
  app.innerHTML=topbar(s.name,`${s.products.length} prodotti`,true)+`<main><div class="section-head"><h2>Prodotti</h2><button onclick="editProduct('${s.id}')">+ Prodotto</button></div>${s.products.length?s.products.map(p=>`<section class="card product ${p.qty>0?'selected':''}" draggable="true" ondragstart="dragProductStart(event,'${p.id}')" ondragover="event.preventDefault()" ondrop="dropProduct(event,'${p.id}')"><div class="prod-top"><span class="handle">≡</span><div class="prod-main"><div class="prod-name">${esc(p.name)}</div><div class="prod-sub">${euro(p.price)} · ${esc(p.unit)} · minimo ${p.minQty}</div></div><button class="dots" onclick="productMenu('${s.id}','${p.id}')">⋮</button></div><div class="stepper"><button onclick="changeQty('${s.id}','${p.id}',-1)">−</button><div><div class="qty">${p.qty}</div><div class="qtylabel">Quantità</div></div><button class="plus" onclick="changeQty('${s.id}','${p.id}',1)">+</button></div><div class="product-foot quick-note-foot"><span class="min-label">Minimo ${p.minQty} ${esc(p.unit)}</span><button class="quick-note ${p.note?'has-note':''}" onclick="quickNote('${s.id}','${p.id}')">${p.note?'Nota ✓':'Nota +'}</button><strong>${euro(p.price*p.qty)}</strong></div></section>`).join(''):'<div class="empty">Nessun prodotto.</div>'}</main><div class="bottom-summary"><div class="bottom-inner"><div class="grow"><small>${itemCount(s)} unità</small><strong>${euro(total(s))}</strong></div><button onclick="shareOne('${s.id}')">WhatsApp</button></div></div>`;
}



// ===== v1.8.0 categorie fornitori =====
const LAST_CAT='ordini_last_category_v18',ALL_CAT='__all__';
let selectedCategory=localStorage.getItem(LAST_CAT)||ALL_CAT;
function ensureSelectedCategory(){if(selectedCategory!==ALL_CAT&&!state.categories.some(c=>c.id===selectedCategory))selectedCategory=ALL_CAT;localStorage.setItem(LAST_CAT,selectedCategory)}
function categoryById(id){return state.categories.find(c=>c.id===id)}
function categoryCount(id){return state.suppliers.filter(s=>!s.archived&&s.categoryId===id).length}
function selectCategory(id){selectedCategory=id;ensureSelectedCategory();render()}
function categoryTabs(){ensureSelectedCategory();return `<div class="category-tabs"><button class="category-tab ${selectedCategory===ALL_CAT?'active':''}" onclick="selectCategory('${ALL_CAT}')">Tutti</button>${state.categories.map(c=>`<button class="category-tab ${selectedCategory===c.id?'active':''}" onclick="selectCategory('${c.id}')">${esc(c.name)}</button>`).join('')}</div>`}

function home(){
  ensureSelectedCategory();let now=new Date(),mt=monthTotal(now.getFullYear(),now.getMonth()),allActive=state.suppliers.filter(s=>!s.archived),active=selectedCategory===ALL_CAT?allActive:allActive.filter(s=>s.categoryId===selectedCategory),title=selectedCategory===ALL_CAT?'Tutti i fornitori':(categoryById(selectedCategory)?.name||'Fornitori');
  app.innerHTML=topbar('Ordini Fornitori',`Speso a ${monthLabel(now.getFullYear(),now.getMonth())}: ${euro(mt)}`)+`<main><div class="hero"><div class="row"><div><div class="label">Ordine corrente</div><div class="money">${euro(allActive.reduce((a,s)=>a+total(s),0))}</div><div class="label">${allActive.reduce((a,s)=>a+itemCount(s),0)} unità selezionate</div></div><button onclick="showStats()">Statistiche</button></div></div>${categoryTabs()}<div class="section-head"><h2>${esc(title)}</h2><button onclick="editSupplier()">+ Fornitore</button></div><div class="supplier-grid">${active.length?active.map(s=>`<section class="card compact" draggable="true" data-supplier="${s.id}" ondragstart="dragStart(event)" ondragover="event.preventDefault()" ondrop="dropSupplier(event,'${s.id}')"><div class="supplier-head"><span class="handle">≡</span><div class="supplier-info"><div class="supplier-name">${esc(s.name)}</div><div class="meta">${selectedCount(s)} prodotti selezionati · ${itemCount(s)} unità</div><div class="amount">${euro(total(s))}</div></div><button class="dots" onclick="supplierMenu('${s.id}')">⋮</button></div><div class="actions"><button class="btn primary flex" onclick="openSupplier('${s.id}')">Apri</button></div></section>`).join(''):'<div class="empty">Nessun fornitore in questa categoria.</div>'}</div></main>${orderBottom(allActive)}`;
}

function chooseCategoryModal(title,currentId,onChoose){
  modal(`<h3>${esc(title)}</h3><div class="category-choice-list">${state.categories.map(c=>`<button class="category-choice ${c.id===currentId?'active':''}" data-cid="${c.id}" onclick="document.querySelectorAll('.category-choice').forEach(x=>x.classList.remove('active'));this.classList.add('active')">${esc(c.name)}</button>`).join('')}</div><div class="modal-actions"><button class="btn secondary" onclick="closeModal()">Annulla</button><button class="btn primary" id="catConfirm">Conferma</button></div>`,null,false);
  $('#catConfirm').onclick=()=>{const b=document.querySelector('.category-choice.active');if(!b)return alert('Scegli una categoria.');const cid=b.dataset.cid;closeModal();onChoose(cid)};
}
function editSupplier(id=null){
  let s=id?supplier(id):null,defaultId=s?.categoryId||(selectedCategory!==ALL_CAT?selectedCategory:state.categories[0]?.id);
  editSupplierForm(s,defaultId,s?.name||'');
}
function editSupplierForm(s,chosen,nameValue){
  modal(`<h3>${s?'Modifica':'Nuovo'} fornitore</h3><div class="field"><label>Nome</label><input id="mname" value="${esc(nameValue||'')}" placeholder="Nome fornitore"></div><div class="field"><label>Categoria</label><button class="category-select-btn" id="supplierCatBtn">${esc(categoryById(chosen)?.name||'Scegli categoria')}</button></div>`,()=>{let n=$('#mname').value.trim();if(!n)return;if(!chosen)return alert('Scegli una categoria.');if(s){s.name=n;s.categoryId=chosen}else state.suppliers.push({id:uuid(),name:n,archived:false,categoryId:chosen,products:[]});save();closeModal();render()});
  $('#supplierCatBtn').onclick=()=>{const typed=$('#mname').value;chooseCategoryModal('Scegli categoria',chosen,cid=>editSupplierForm(s,cid,typed))};
}

function supplierMenu(id){let s=supplier(id);modal(`<h3>${esc(s.name)}</h3><button class="menuitem" onclick="closeModal();editSupplier('${id}')">✎ Modifica</button><button class="menuitem" onclick="moveSupplierCategory('${id}')">▤ Sposta in categoria</button><button class="menuitem" onclick="duplicateSupplier('${id}')">⧉ Duplica fornitore</button><button class="menuitem" onclick="archiveSupplier('${id}')">▣ Archivia fornitore</button>`,null,false)}
function moveSupplierCategory(id){let s=supplier(id);chooseCategoryModal(`Sposta ${s.name}`,s.categoryId,cid=>{s.categoryId=cid;save();render()})}
function duplicateSupplier(id){let s=supplier(id),i=state.suppliers.indexOf(s);state.suppliers.splice(i+1,0,{id:uuid(),name:s.name+' (copia)',archived:false,categoryId:s.categoryId,products:s.products.map(p=>({...p,id:uuid(),qty:0}))});save();closeModal();render()}
function archiveSupplier(id){let s=supplier(id);if(confirm(`Archiviare ${s.name}?`)){snapshotUndo();s.archived=true;s.categoryId='';s.products.forEach(p=>{p.qty=0;p.note=''});save();closeModal();render();offerUndo('Fornitore archiviato')}}

function manageCategories(){closeDrawer();modal(`<h3>Gestisci categorie</h3><button class="btn primary wide" onclick="newCategory()">+ Nuova categoria</button><div class="manage-cats">${state.categories.map((c,i)=>`<div class="manage-cat"><div><b>${esc(c.name)}</b><small>${categoryCount(c.id)} fornitori</small></div><div class="manage-cat-actions"><button onclick="moveCategory(${i},-1)">↑</button><button onclick="moveCategory(${i},1)">↓</button><button onclick="renameCategory('${c.id}')">✎</button><button class="danger-mini" onclick="deleteCategory('${c.id}')">×</button></div></div>`).join('')}</div>`,null,false)}
function newCategory(){let n=prompt('Nome nuova categoria:');if(!n?.trim())return;state.categories.push({id:uuid(),name:n.trim()});save();closeModal();manageCategories();render()}
function renameCategory(id){let c=categoryById(id),n=prompt('Nuovo nome categoria:',c.name);if(!n?.trim())return;c.name=n.trim();save();closeModal();manageCategories();render()}
function moveCategory(i,d){let j=i+d;if(j<0||j>=state.categories.length)return;let c=state.categories.splice(i,1)[0];state.categories.splice(j,0,c);save();closeModal();manageCategories();render()}
function deleteCategory(id){let c=categoryById(id),n=categoryCount(id);if(!confirm(`La categoria “${c.name}” contiene ${n} fornitor${n===1?'e':'i'}. Eliminandola, tutti i fornitori verranno spostati nell'Archivio fornitori. Continuare?`))return;snapshotUndo();state.categories=state.categories.filter(x=>x.id!==id);state.suppliers.forEach(s=>{if(!s.archived&&s.categoryId===id){s.archived=true;s.categoryId='';s.products.forEach(p=>{p.qty=0;p.note=''})}});if(!state.categories.length)state.categories.push({id:uuid(),name:'Generale'});if(selectedCategory===id)selectedCategory=ALL_CAT;ensureSelectedCategory();save();closeModal();render();offerUndo('Categoria eliminata e fornitori archiviati')}

function archiveView(){let ar=state.suppliers.filter(s=>s.archived);app.innerHTML=topbar('Fornitori archiviati',`${ar.length} archiviati`,true)+`<main>${ar.length?ar.map(s=>`<section class="card compact"><div class="supplier-name">${esc(s.name)}</div><div class="meta">${s.products.length} prodotti</div><div class="actions"><button class="btn primary flex" onclick="restoreSupplier('${s.id}')">Ripristina</button><button class="btn danger" onclick="hardDeleteSupplier('${s.id}')">Elimina</button></div></section>`).join(''):'<div class="empty">Archivio vuoto.</div>'}</main>`}
function restoreSupplier(id){let s=supplier(id);chooseCategoryModal(`Categoria per ${s.name}`,'',cid=>{s.categoryId=cid;s.archived=false;save();render()})}
function hardDeleteSupplier(id){let s=supplier(id);if(confirm(`Eliminare definitivamente ${s.name}? Lo storico resterà disponibile.`)){snapshotUndo();state.suppliers=state.suppliers.filter(x=>x.id!==id);save();render();offerUndo('Fornitore eliminato')}}

function openDrawer(){let el=document.createElement('div');el.className='drawer-back';el.id='drawerBack';el.onclick=e=>{if(e.target===el)el.remove()};el.innerHTML=`<aside class="drawer"><h2>Ordini Fornitori</h2><p>PWA v1.8.2</p><button class="menuitem" onclick="closeDrawer();showHistory()">◷ <span>Storico ordini</span></button><button class="menuitem" onclick="closeDrawer();showStats()">▥ <span>Spesa mensile</span></button><button class="menuitem" onclick="manageCategories()">▤ <span>Gestisci categorie</span></button><button class="menuitem" onclick="closeDrawer();showArchive()">▣ <span>Fornitori archiviati (${state.suppliers.filter(s=>s.archived).length})</span></button><hr><button class="menuitem" onclick="exportLists()">⇧ <span>Esporta liste</span></button><button class="menuitem" onclick="exportFull()">⬆ <span>Esporta backup completo</span></button><button class="menuitem" onclick="$('#importFile').click()">⇩ <span>Importa backup/liste</span></button><button class="menuitem" onclick="restoreInternal()">↶ <span>Ripristina backup automatico</span></button><button class="menuitem" onclick="accentPicker()">◉ <span>Colore principale</span></button><button class="menuitem" onclick="toggleTheme()">◐ <span>Modalità chiara/scura</span></button></aside>`;document.body.appendChild(el)}
function exportLists(){let x={format:'OrdiniFornitoriBackup',version:6,categories:state.categories,suppliers:state.suppliers.map(s=>({...s,products:s.products.map(p=>({...p,qty:0}))}))};downloadJson(x,'ordini-fornitori-liste.json')}
function exportFull(){downloadJson({...state,format:'OrdiniFornitoriFullBackup',schemaVersion:7,createdAt:Date.now(),ui:{theme:localStorage.getItem(THEME)||'light',accent:localStorage.getItem('ordini_accent')||'blue'}},'ordini-fornitori-backup-completo.json')}

ensureSelectedCategory();applyAccent(localStorage.getItem('ordini_accent')||'blue');render();
